name: CraftClan
main: fr.insynia.craftclan.Base.CraftClanPlugin
version: 1.0
depend: [InventoryApi]
commands:
   cc:
      description: Every user command.
      usage: /<command> [command] [command arguments]
   cca:
      description: Admin restricted command.
      usage: /<command> [command] [command arguments]


