name: CraftClanPlugin
main: fr.insynia.craftclan.CraftClanPlugin
version: 1.0
commands:
   addpoint:
      description: Add a point to your position.
      usage: /<command> [name] [radius]
   addfaction:
      description: Add a faction.
      usage: /<command> [name] [color] [level]
   gofaction:
      description: Add a faction.
      usage: /<command> [name] [color] [level]
   pointfaction:
      description: Add a faction.
      usage: /<command> [name] [color] [level]
   ccselect:
      description: Select a zone to save.
      usage: /<command> [x] [y] [z]
   spawnStructure:
      description: Spawn structures.
      usage: /<command> [name]
   ccsave:
      description: Save structure.
      usage: /<command> [name]
   ccread:
      description: Read a file.
      usage: /<command> [folder] [filename]

